# Generated by Django 5.0.7 on 2024-08-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='realese_year',
            new_name='release_year',
        ),
    ]
